### PR TITLE
fix: sharing url for unicode

### LINKED ISSUE #17: Chinese and unicode are not supported
When the path contains Chinese or αβγ The QR code URL is garbled
image

### PR DESCRIPTION
**Pull request by colgin**
fix: [issue](https://github.com/parvardegr/sharing/issues/17)

### CODE REVIEW

File: bin/index.js [hunk 1]
```diff
@@ -83,7 +83,7 @@ var getNetworkAddress = () => {
         let file = '';
         if (fileName) {
             usageMessage = `Scan the QR-Code to access '${fileName}' file on your phone`;
-            file = '/' + fileName;
+            file = '/' + encodeURIComponent(fileName);
```
Comment (parvardegr) [inline bin/index.js:86]: @colgin 
great! but if you do this when we have the full `shareAddress` we can support Unicode for directory names too.
you can do something like this after line 94: `shareAddress  = encodeURI(shareAddress)`

thank you for this cool PR

Comment (colgin) [reply bin/index.js:86]: Actually, Unicode directory is supported now. 
```bash
sharing ./测试
```
it works!

Moreover, browser will encode the url automantically when we click the a element.

So, I think it's unnecessary to encode the whole address.
